#!/usr/bin/python3 -u
"""
Description: Game wrapper to set environment variables and enable things like
gamescope and mangohud with one centralized configuration.
Author: thnikk
"""
from subprocess import run, Popen, DEVNULL, STDOUT, CalledProcessError
import signal
import os
import sys
import argparse
import json
import glob
import re
import time
from datetime import datetime
import threading
import psutil


def args_setup():
    """ Set up argparse"""
    # Set up argparse
    parser = argparse.ArgumentParser(
        prog='pygame',
        description="""Game wrapper to set environment variables and enable
        things like gamescope and mangohud with one centralized
        configuration.""",
        epilog='Config file is located at ~/.config/pygame.json'
    )
    parser.add_argument(
        '-p', '--prime', action='store_true',
        help='Disable prime if configured')
    parser.add_argument(
        '-g', '--gamescope', action='store_true', help='Enable gamescope')
    parser.add_argument(
        '-m', '--mangohud', action='store_true', help='Enable mangohud')
    parser.add_argument(
        '-a', '--mangoapp', action='store_true', help='Enable mangoapp')
    parser.add_argument(
        '-M', '--gamemode', action='store_true', help='Enable gamemode')
    parser.add_argument(
        '-r', action='store_true', help='Disable reaper')
    parser.add_argument(
        '-c', '--cursor', action='store_true',
        help='Force grab cursor in gamescope')
    parser.add_argument(
        '-x', '--x11', action='store_true',
        help='Force gamescope to run in x11 mode')
    parser.add_argument(
        '-l', '--log', action='store_true',
        help='Save process output to logfile at ~/.cache/pygame.log')
    parser.add_argument(
        '-o', '--opengl', action='store_true',
        help='Specify that game uses OpenGL for mangohud')
    parser.add_argument(
        '-W', '--width', help='Output width override')
    parser.add_argument(
        '-H', '--height', help='Output height override')
    parser.add_argument('command', nargs=argparse.REMAINDER)
    args = parser.parse_args()

    if not args.command:
        parser.print_help()
        sys.exit(1)
    return args


def command_exists(command) -> bool:
    """ Check if command exists """
    try:
        run(["which", command],
            stdout=DEVNULL,
            stderr=DEVNULL,
            check=True)
        return True
    except CalledProcessError:
        print(f"{command} doesn't exist.")
        return False


def pkill(progs) -> None:
    """ Kill list of programs """
    for prog in progs:
        run(['pkill', prog], check=False)


def get_env(env_user) -> dict:
    """ Get dictionary of environment variables """
    env_os = os.environ.copy()
    env_os.update(env_user)
    return env_os


def get_json_dict(path, default) -> dict:
    """ Get dict from json file """
    try:
        with open(path, 'r', encoding='utf-8') as file:
            output = file.read()
            output = re.sub(re.compile(r"/\*.*?\*/", re.DOTALL), "", output)
            output = re.sub(re.compile(r"//.*?\n"), "", output)
            return json.loads(output, parse_int=str, parse_float=str)
    except FileNotFoundError:
        with open(path, 'w', encoding='utf-8') as file:
            file.write(json.dumps(default, indent=4))
        output = default
    return output


def get_device_path(vid_pid) -> str:
    """ Get path to card """
    def get_id(path) -> str:
        """ Get ID from file """
        with open(path, 'r', encoding='utf-8') as file:
            return file.read().lstrip('0x').rstrip().lower()

    for path in glob.glob('/sys/bus/pci/devices/*'):
        try:
            vendor = get_id(f'{path}/vendor')
            product = get_id(f'{path}/device')
            if f'{vendor}:{product}' == vid_pid.lower():
                return f'''pci-{path.split("/")[-1].replace(
                    ":", "_").replace(".", "_")}'''
        except NotADirectoryError:
            pass
    raise ValueError('vid:pid not found.')


def get_tree(pid) -> list:
    """ Get process tree of given PID """
    parent = psutil.Process(pid)
    return parent.children(recursive=True)


def kill(processes, sig="SIGTERM") -> None:
    """ Kill process list with signal """
    for process in processes:
        # Don't kill main process first
        if process.name == 'pygame':
            continue
        try:
            print(f'Sending {sig} to {process.name()} [{process.pid}]',
                  file=sys.stderr)
            run(['kill', f'-{sig}', f'{process.pid}'],
                check=True, capture_output=False,
                stdout=DEVNULL, stderr=STDOUT)
        except (CalledProcessError, ValueError, psutil.NoSuchProcess):
            # print(f"Couldn't kill {pid}.")
            pass


def generate_command(args, steam, config):
    """ Generate main command to run """
    # Create command
    command = []
    # if 'prime' in config and config['prime']:
    #     prime = ['env', f"DRI_PRIME={get_device_path(config['prime'])}"]
    if args.gamescope:
        try:
            width = args.width or config["width"]
            height = args.height or config["height"]
        except KeyError:
            print(
                'Must specify width and height in arguments or configuration.')
            sys.exit(1)
        if command_exists('gamescope'):
            gamescope = [
                "gamescope",
                "-w", width,
                "-W", width,
                "-h", height,
                "-H", height,
                "--filter", "fsr",
                "--fsr-sharpness", "0",
                "--rt",
                "-f", "--"
            ]
            if steam:
                gamescope.insert(-2, '-e')
            if args.cursor or ('cursor' in config and config['cursor']):
                gamescope.insert(-2, '--force-grab-cursor')
                gamescope.insert(-2, '--mouse-sensitivity=1.25')
            if args.x11 or ('x11' in config and config['x11']):
                gamescope.insert(-2, '--backend=sdl')
            if ('mangoapp' in config and config['mangoapp']) or args.mangoapp:
                gamescope.insert(-2, '--mangoapp')
            command = command + gamescope

    # if prime and not args.prime:
    #     command = command + prime

    if args.gamemode:
        if command_exists('gamemoderun'):
            command = command + ["gamemoderun"]
    if args.mangohud and args.opengl and not (
        'mangoapp' in config and config['mangoapp']
    ):
        if command_exists('mangohud'):
            command = command + ["mangohud", '--dlsym']
    return command + args.command


def sigterm_handler(signum, *_):
    """ Ignore sigterm """
    print(f'Received signal {signum}')
    if signum == 15:
        tree = get_tree(os.getpid())
        print(f'pygame pid: {os.getpid()}')
        print(f'process tree: {tree}')
        # cleanup(tree)
        kill(tree, 'SIGKILL')


def reaper(pid):
    time.sleep(1)
    print('Reaper thread started.')
    tree = get_tree(pid)
    last_tree = tree
    while True:
        tree = get_tree(pid)
        # Filter out gamescope and mangoapp
        stripped = []
        for item in last_tree:
            try:
                name = item.name()
            except psutil.NoSuchProcess:
                continue
            if 'gamescope' not in name and 'mangoapp' not in name:
                stripped.append(item)
        try:
            # Raise error if game process isn't in the tree
            if stripped[0] not in tree:
                raise ValueError
        except (IndexError, ValueError):
            print('Reaper thread killing tree.')
            # print("Killing:", last_tree)
            kill(last_tree, "SIGKILL")
            return
        last_tree = tree
        time.sleep(1)


def main() -> None:
    """ Main function """
    signal.signal(signal.SIGTERM, sigterm_handler)
    signal.signal(signal.SIGINT, sigterm_handler)
    args = args_setup()

    if not args.r:
        reaper_thread = threading.Thread(target=reaper, args=[os.getpid()])
        reaper_thread.start()

    steam = 'steam' in ''.join(args.command).lower()

    # Load config
    default = {
        'config': {'prime': '1002:73bf', 'width': '2560', 'height': '1440'},
        'env': {'SDL_VIDEODRIVER': 'x11'}
    }

    config_full = get_json_dict(
        os.path.expanduser('~/.config/pygame.json'), default)
    config = config_full['config']
    env = config_full['env']
    env['WINEDEBUG'] = '-all'

    # Enable PRIME offloading
    try:
        if config['prime'] and not args.prime:
            env['DRI_PRIME'] = \
                get_device_path(config['prime'])
        else:
            print('Prime disabled.')
            env['DRI_PRIME'] = "0"
    except (ValueError, KeyError):
        pass

    # Enable mangohud/mangoapp
    if args.mangohud and not args.opengl and (
        'mangoapp' not in config or not config['mangoapp']
    ):
        env['MANGOHUD'] = '1'

    # Set SDL backend for gamescope if x11 is set to true
    if args.x11 or ('x11' in config and config['x11']):
        env['SDL_VIDEODRIVER'] = "x11"

    # Generate full command to run
    command = generate_command(args, steam, config)

    logpath = os.path.expanduser('~/.cache/pygame.log')
    # Run command and log output to file
    if args.log or ('log' in config and config['log']):
        with open(logpath, 'w', encoding='utf-8') as logfile:
            with Popen(
                command, env=get_env(env),
                stdout=logfile, stderr=logfile
            ) as proc:
                print('Running command:', *proc.args)
                print(f'Logging command output to {logpath}')
                # Update process tree
                time.sleep(10)
                tree = get_tree(os.getpid())
    else:
        with Popen(
            command, env=get_env(env), stdout=DEVNULL, stderr=DEVNULL
        ) as proc:
            # Update process tree
            time.sleep(10)
            tree = get_tree(os.getpid())

    with open(logpath, 'a', encoding='utf-8') as logfile:
        print(
            f'[{datetime.now().timestamp()}] pygame pid: {os.getpid()}',
            file=logfile)
        print(
            f'[{datetime.now().timestamp()}] process tree: {tree}',
            file=logfile)


if __name__ == "__main__":
    main()
